-- Run once against an empty funeral_management database.
-- The transaction prevents a partially created schema if any statement fails.
BEGIN;

CREATE TABLE ceremony_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 3) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT chk_ceremony_types_name CHECK (btrim(name) <> '')
);

CREATE TABLE request_statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 6) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT chk_request_statuses_name CHECK (btrim(name) <> '')
);

INSERT INTO ceremony_types (id, name) VALUES
    (1, 'Захоронение'),
    (2, 'Кремация');

INSERT INTO request_statuses (id, name) VALUES
    (1, 'Новая'),
    (2, 'Подтверждена'),
    (3, 'В процессе'),
    (4, 'Завершена'),
    (5, 'Отменена');

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_clients_phone UNIQUE (phone),
    CONSTRAINT uq_clients_email UNIQUE (email),
    CONSTRAINT chk_clients_full_name CHECK (btrim(full_name) <> ''),
    CONSTRAINT chk_clients_phone CHECK (btrim(phone) <> ''),
    CONSTRAINT chk_clients_email CHECK (email IS NULL OR btrim(email) <> '')
);

CREATE TABLE funeral_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    deceased_full_name VARCHAR(255) NOT NULL,
    ceremony_date DATE NOT NULL,
    ceremony_type_id INTEGER NOT NULL,
    status_id INTEGER NOT NULL DEFAULT 1,
    price NUMERIC(12, 2) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_funeral_requests_client
        FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE RESTRICT,
    CONSTRAINT chk_funeral_requests_deceased_name
        CHECK (btrim(deceased_full_name) <> ''),
    CONSTRAINT chk_funeral_requests_price
        CHECK (price >= 0 AND price <> 'NaN'::numeric),
    CONSTRAINT fk_funeral_requests_ceremony_type
        FOREIGN KEY (ceremony_type_id) REFERENCES ceremony_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_funeral_requests_status
        FOREIGN KEY (status_id) REFERENCES request_statuses (id) ON DELETE RESTRICT
);

-- PostgreSQL does not automatically index the referencing side of a foreign key.
CREATE INDEX idx_funeral_requests_client_id ON funeral_requests (client_id);

COMMIT;
