CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(25) NOT NULL,
    email VARCHAR(254)
);

CREATE TABLE IF NOT EXISTS funeral_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    deceased_full_name VARCHAR(150) NOT NULL,
    ceremony_date DATE NOT NULL,
    ceremony_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    comment VARCHAR(1000),
    CONSTRAINT fk_funeral_requests_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE INDEX IF NOT EXISTS idx_funeral_requests_client_id
    ON funeral_requests (client_id);

CREATE INDEX IF NOT EXISTS idx_funeral_requests_ceremony_date
    ON funeral_requests (ceremony_date);

CREATE INDEX IF NOT EXISTS idx_funeral_requests_status
    ON funeral_requests (status);
